### PR TITLE
Add Pixel 4x5 grid and larger icons for low grid sizes (PR #10 contd.)

### PR DESCRIPTION
**Pull request by yihanwu1024**
Use Pixel Launcher dimensions ([Issue 1513](https://github.com/GrapheneOS/os-issue-tracker/issues/1513)). This also adds a 4 by 5 grid size, which has been the default on Pixel devices since Android 12.

This patch is now compatible with QPR1.

### CODE REVIEW

**Comment by thestinger** [comment]
I think this makes sense but my one concern is that we'll be adding yet another thing we need to port to each new quarterly and yearly release. Are you willing to join our contributor chat channel (can invite you if you join #dev:grapheneos and message me) and try to help us out with that and perhaps porting a few other small things?

**Comment by yihanwu1024** [comment]
Yes, I am joining the chat.

**Comment by c---** [comment]
If this is going to be incorporated would it be possible to include other modes as well? For example a 5x7 mode or the 6x grids like LineageOS has. 5x7 would match the App Drawer on the longer Pixel phones. Right now it's really disorienting when you switch between the home screen and the App Drawer.

LineageOS also has modes like 5x6 which could be useful. In this case it might only make sense if that fits a particular Pixel model.

**Comment by yihanwu1024** [comment]
> If this is going to be incorporated would it be possible to include other modes as well? For example a 5x7 mode or the 6x grids like LineageOS has. 5x7 would match the App Drawer on the longer Pixel phones. Right now it's really disorienting when you switch between the home screen and the App Drawer.
> 
> LineageOS also has modes like 5x6 which could be useful. In this case it might only make sense if that fits a particular Pixel model.

Sounds okay. In fact, according to my tests, when 5x7 is applied on recent (longer) Pixels, the grid looks most evenly distributed, i.e. each cell is almost 1:1 square.

But my commit wasn't merged despite one guy from GrapheneOS showing some level of recognition of this patch. I don't know what they are thinking.

At this time of 2023 we may want to add a tablet layout as well, ahead of Pixel Tablet launch.

**Comment by thestinger** [comment]
@yihanwu1024 It needs to be rebased and submitted for Android 15 if you're still interested in it. The main reason it wasn't merged is a combination of it not being kept rebased and the low priority for this.

**Pull request closed without merging**
