### PR TITLE
Launcher3: Add 5x6, 5x7 and 6x6 default workspaces

### PR DESCRIPTION
**Pull request by x86pup**
Cherry-picked from https://github.com/ProtonAOSP/android_packages_apps_Launcher3/commit/6032e133302178d450a5b681ea4ebb18aee792d9

Solves https://github.com/GrapheneOS/os-issue-tracker/issues/1599

Tested with emulator, works fine

### CODE REVIEW

**Comment by thestinger** [comment]
Don't know if this is wanted. Does the stock OS have these?

**Comment by x86pup** [comment]
@thestinger Only 6x5 https://9to5google.com/2022/06/08/pixel-launcher-tablet-6x5-grid/

Also looking at this, I need to actually make some changes to these XML files to match our existing grid options. Just let me know if this is wanted or not

**Comment by ruvilonix** [comment]
I would like this. I miss the larger grid on LineageOS.

**Comment by jorgeah92** [comment]
I know is this old and closed, but I would also like more grid sizes. The square is not always ideal for these candy bar shaped phones.

**Pull request closed without merging**
