### PR TITLE
[temp] add a hardwired bottom padding of 16dp.

### LINKED ISSUE #2032: Misaligned background behind the search bar
After an update, the search bar in the launcher has a misaligned background

IMG_20230316_083605

### PR DESCRIPTION
**Pull request by empratyush**
closes [#2032](https://github.com/GrapheneOS/os-issue-tracker/issues/2032)

### CODE REVIEW

**Comment by juxuanu** [comment]
This doesn't look alright.

Screenshot_20230412-113613_1

**Comment by lokesh-krishna** [comment]
Came to to ask about the same. The icons pass above the tint while the text passes underneath it. Intuitively, one would expect both to pass underneath the tint. 

Is the present behaviour intentional?

**Comment by thestinger** [comment]
It's meant to be the same as the Pixel Launcher.

**Comment by thestinger** [comment]
This is part of the AOSP Launcher, which matches an older version of the Pixel Launcher. The size of this background wasn't large enough for the larger search box but it otherwise seems fine. We're not going to waste substantial resources tweaking the appearance of it especially because it mostly matches the Pixel Launcher now.

**Pull request merged**
